import pymysql.cursors


class Config(object):
    # 间隔时间
    interval = 6000
    # 故障条件：告警原因里面包含以下条件判断为故障（人工标记）
    condition = ['trafficReplaceableUnitProblem', 'coolingSystemFailure', 'configurationOrCustomisationError',
                 'cntrlBusFail',
                 'trafficReplaceableUnitTypeMismatch', 'internalCommFail', 'coolingFanFailure',
                 'replaceableUnitProblem',
                 'internalFail', 'diskFailure', 'selfTestFail', 'rectifierHighVoltage', 'NE_NOT_LOGIN',
                 'NE_COMMU_BREAK',
                 'backplaneFailure', 'laserTxPowerThresholdHigh', 'txLaserDegraded', 'trafficReplaceableUnitUnknown',
                 'fuseFailure', 'FAN_FAIL', 'Fans Major', 'Card/Slot Fail', 'memoryProblem', 'powerSupplyFailure',
                 'powerProblem',
                 'tempOutOfRange', 'TEMP_ALARM', 'dccFail', 'lossOfSignal', 'farEndReceiverFailure', 'lossOfFrame',
                 'IN_PWR_ABN',
                 'Degraded Signal', 'Loss Of Frame', 'Loss Of Signal', 'LOF', 'Temperature Out Of Range',
                 'High Temperature',
                 'Sfwr Environment Problem', 'HouseKeeping', 'Housekeeping Alarm', 'And Battery Failure',
                 'Battery Failure',
                 'PWRSUSP', 'PWR', 'Power Failure', 'VOLTAGELOW', 'Inside Failure', 'Underlying Resource Unavailable',
                 'Replaceable Unit Problem', 'MIB backup misaligned', 'Internal Communication Problem',
                 'Replaceable Unit Missing', 'Transport Failure', 'Transport Outgoing Failure', 'Fuse Failure',
                 'Transmitter Failure', 'Equipment Failure', 'Cooling Fan Failure', 'PWRADJFAIL',
                 'NE not reachable by Control Plane',
                 'FANSPEEDHIGH', 'Pump Failure', ' LossOfSignal', 'fanFailure', ' PowerProblem', 'RSM_配置采集单元（探针）异常',
                 ' TransmitterFailure', 'TransmissionError', ' fanDegraded', 'BackupFailed', 'fanDegraded',
                 'Loss Of Signal',
                 'Loss Of Frame', 'Equipment power failure at connector B', 'Equipment power failure at connector A',
                 'Equipment power failure at return connector A', 'Equipment Failure', 'Fan Failure',
                 'Equipment Low Tx power',
                 'Optical Amplifier Gain Degrade Low', 'LOF', 'TempHighAlarm', 'PKG_FAIL', 'FAN_FAIL', 'BUS_ERROR',
                 'LAPS_FAIL',
                 'MEM_FAIL', 'FCS_ERR', 'R_LOS', 'R_LOF', 'IN_PWR_ABN', 'IN_PWR_LOW', '光模块的接收功率过低', 'TEMP_OVER',
                 'PWR_MAJ_ALM', 'POWER_FAIL', 'TEMP_ALARM', 'POWER_ABNORMAL', 'POWERALM', '电源整体功能失效', 'NE_NOT_LOGIN',
                 'RSM_采集北向接口故障', 'NE_COMMU_BREAK', 'FAN_FAIL', 'BD_STATUS', 'SYN_BAD', 'R_OOF', 'COMMUN_FAIL',
                 'HARD_BAD',
                 'SYSBUS_FAIL', 'BIOS_STATUS', 'BUS_ERR', 'GNE_CONNECT_FAIL', '已配置的单板不能通信', '单板检测到电源故障',
                 'LSR_WILL_DIE', 'OUT_PWR_ABN', 'SUBCARD_ABN', 'BD_NOT_INSTALLED', 'CHIP_ABN', 'PATCH_ERR',
                 'LSR_NO_FITED',
                 'NE_DATA_INCONSISTENCY', 'IN_PWR_FAIL', 'ABNORMAL_PROCESS_STATE', '已配置的单板可以通信，但上报单板故障',
                 '输出板的2M输入均不可用，可能时钟板或LCIM的输出有问题', '输出板的E1输入均不可用，可能时钟板或LCIM的输出有问题',
                 '输出板的10M输入均不可用，可能时钟板或LCIM的输出有问题', 'TODI单板检测不到该DCLS输入源', 'SYNC_FAIL',
                 'IN_PWR_HIGH', 'LASER_MOD_ERR', 'CHIP_FAIL', '数据库需要维护', 'INPWR_FAIL', '光模块拔出',
                 '请检查天线、馈线等硬件连接，并确认天线周围有无强干扰', '光模块整体功能失效', 'CFCARD_FAILED', '防尘网清洗告警',
                 '光模块异常', '风扇整体功能失效', '光模块局部功能失效', '单板电压超过致命阈值', '光模块的接收功率过高',
                 '子卡整体功能失效', '时钟板本振故障。', 'Signal Degrade', 'Loss Of Signal', 'RDI', 'Power Failure - B',
                 'ME loss of communication', 'Circuit Pack Missing', 'Loss Of Shelf Sec. Timing Ref.',
                 'Auto STS3C Path Switch Complete-Sig. Fail', 'Database Save and Restore Failed', 'NE_Backup_Failed',
                 'Comms fail alarm',
                 'Circuit Pack Failed', 'Qecc-Comms_Fail', 'Duplicate Shelf Detected', 'OS-Optical_Power_High',
                 'Fan Failed',
                 'Internal Mgmt Comms Suspected', 'Circuit Pack Missing - Pluggable', 'Client Service Mismatch',
                 'Circuit Pack Upgrade Failed', 'I/O Module Missing', 'Circuit Pack Failed - Sync',
                 'Circuit Pack Mismatch',
                 'Circuit Pack Mismatch - Pluggable', 'Bipolar Violations', 'Corrupt Inventory Data', 'lossOfSignal',
                 'STM16光物理接口 信号丢失(LOS)', '激光器温度越限', '探测点温度越限', 'detectTemp', 'LsrTemp-TCA',
                 '探测点温度(℃)越限', '-48V电源分配箱1高压告警', '-48V电源分配箱2无输入', '-48V电源输入Sci无输入', 'powerSciLow',
                 '-48V电源输入Sci低压告警', 'powerSciNoInput', 'powerBox2Port2NoInput', 'powerQxiHigh', 'powerSciHigh',
                 'powerQxiNoInput', 'powerBox1NoOutput', '-48V电源输入Sci高压告警', '-48V电源输入Qxi高压告警',
                 '-48V电源分配箱1低压告警', '-48V电源分配箱1无输入', '-48V电源分配箱2低压告警', '电源故障', '-48V电源分配箱2高压告警',
                 '-48V电源输入Qxi无输入', '-48V电源输入Qxi低压告警', 'powerProblem', 'powerBAccessFailure', 'powerAAccessFailure',
                 'B路电源接入故障', 'A路电源接入故障', '环境 -48V电源分配箱2无输入', 'coolingFanFailure', '风扇故障',
                 'STM1光物理接口 光模块未认证', 'fanMiss', '应安板未安装', '单板运行不正常', '晶振老化或者时钟参考源频率越界',
                 '风扇故障2', '激光器偏流越限', 'UNKNOWN_CARD', '单板软件运行不正常', '单板 板类型未知', 'PLUGGABLE_TRANSCEIVER_DISMOUNT',
                 '单板 晶振老化或者时钟参考源频率越界', 'ABSENCE_WARNING', '背板总线错', '单板 应安板未安装', '单板 板类型失配',
                 'SHELF_ABSENCE', '单板 电源故障', '环境 风扇2故障', '环境 风扇故障', 'LOS', 'PWR_FAIL', 'PWRL_NFB_B', 'FAN',
                 'Association Failed', 'FAN_FAIL', 'PKG_FAIL', 'COMM_FAIL', 'BUS_FAIL', 'CONTBUS_RMV', 'CPU_FAIL',
                 'LOS', 'Service Degraded',
                 'IN_PWR_ABN', 'RX-oPower-L-Warning', 'RX-oPower-Low',
                 'Optical Power High Back Reflection,[sub_slot=2]',
                 'High Temperature', 'Temperature-TC', 'TEMP_ALARM', 'High Temperature Pump', 'TEMP_OVER',
                 'Low Temperature',
                 'High Temperature,[sub_slot=33]', 'ENV-Temp-High', 'MCP-Start-Fail', 'Power Failure', 'POWER_ABNORMAL',
                 'POWER_FAIL', 'DC-IN-Fail', 'Input Voltage 1 Failure', 'Air Flow', 'High Tx Power', 'Service Failure',
                 'Disconnection',
                 'Low Tx Power', 'Laser Bias High', 'AN Failure', 'BD_STATUS', 'FAN_FAIL', 'COMMUN_FAIL',
                 'NE_COMMU_BREAK',
                 'NE_NOT_LOGIN', 'Fan-FAIL', 'Programming Fault', 'Communication Failure',
                 'Low Tx Power ,[sub_slot=33]', 'Card Failure',
                 'Card-Fail']
    # 连接配置信息
    sql_config = {
        'host': '172.16.135.6',
        'port': 3306,
        'user': 'root',
        'password': '10086',
        'db': 'hunan',
        'charset': 'utf8',
        'cursorclass': pymysql.cursors.DictCursor,
    }
    # 数据开始时间,结束时间
    start_time = '2016--01--03'
    end_time = '2018--04--20'
